export const PEOPLE = [
  {
    slug: "sultan-bin-sulayem",
    name: "Sultan Bin Sulayem",
    title: "Chairman, DP World / Port of Dubai",
    countries: ["Nigeria", "Senegal", "Somalia", "Kenya", "Ivory Coast", "Zimbabwe", "Ethiopia", "Africa"],
    bio: "Sultan Ahmed Bin Sulayem is the Group Chairman and CEO of DP World, one of the world's largest port operators, headquartered in Dubai. He appears in 76 emails in Epstein's archive — the highest volume of any Africa-connected correspondent. Threads involve an Africa trip with Epstein, Nigeria port discussions, Senegal political coverage, Somaliland recognition documents, and references to African business figures including Aliko Dangote. His correspondence spans 2010–2018.",
    searchTerms: ["sultan", "sultan bin sulayem"],
  },
  {
    slug: "jeffrey-epstein",
    name: "Jeffrey Epstein",
    title: "Financier (subject of investigation)",
    countries: ["Kenya", "Nigeria", "South Africa", "Senegal", "Somalia", "Zimbabwe", "Africa"],
    bio: "Jeffrey Epstein is the central subject of this database. His Africa-related correspondence includes visa arrangements for Kenya trips (2009), discussions of African business ventures, and forwarded materials on African political affairs. He was arrested in 2019 and died in federal custody the same year.",
    searchTerms: ["jeffrey epstein", "j. epstein", "jeeproject", "jeevacation", "jeffrey e."],
  },
  {
    slug: "peggy-siegal",
    name: "Peggy Siegal",
    title: "New York publicist",
    countries: ["Africa"],
    bio: "Peggy Siegal is a prominent New York entertainment publicist who appears in Epstein's Africa-related email archive. She was previously reported as a social contact of Epstein's.",
    searchTerms: ["peggy siegal", "peggy"],
  },
  {
    slug: "jide-zeitlin",
    name: "Jide Zeitlin",
    title: "Former CEO, Tapestry Inc.",
    countries: ["Nigeria", "Africa"],
    bio: "Adebayo 'Jide' Zeitlin is a Nigerian-American business executive who served as CEO of Tapestry Inc. (parent company of Coach). He appears in Epstein's Africa-related correspondence in the context of Nigerian business connections.",
    searchTerms: ["jide zeitlin", "jide", "zeitlin"],
  },
  {
    slug: "lesley-groff",
    name: "Lesley Groff",
    title: "Executive assistant to Jeffrey Epstein",
    countries: ["Kenya", "Africa"],
    bio: "Lesley Groff served as a senior executive assistant to Jeffrey Epstein. She handled logistics including travel arrangements. She appears in Africa-related emails coordinating Epstein's Kenya travel.",
    searchTerms: ["lesley groff", "lesley"],
  },
  {
    slug: "miasha",
    name: "Miasha",
    title: "Epstein contact (identity unconfirmed)",
    countries: ["Africa"],
    bio: "An individual identified only as 'Miasha' appears in Epstein's Africa-related email archive. Full identity has not been confirmed from available documents.",
    searchTerms: ["miasha"],
  },
  {
    slug: "nina-keita",
    name: "Nina Keita",
    title: "Niece of President Alassane Ouattara, Ivory Coast",
    countries: ["Ivory Coast", "Senegal", "Africa"],
    bio: "Nina Keita is the niece of Alassane Ouattara, President of Ivory Coast since 2011. A former model who worked in France before returning to Abidjan, she appears hundreds of times in Epstein's archive — one of the most significant Africa-connected figures in the full dataset. Between 2011 and 2018 she acted as a direct intermediary between Epstein and the Ivorian presidency, introducing him to her uncle and arranging his 2012 Abidjan visit where he met sitting ministers. She also connected Epstein with Sidi Tiémoko Touré, Chef de Cabinet to President Ouattara, and played a central role in efforts to secure the release of Karim Wade from prison in 2015 — emails indicate Epstein sent $100,000 toward lobbying efforts, and when Wade was freed in 2016 she wrote to Epstein: \"Thank you for everything you have done for him.\" She later served as advisor to the Budget Minister, and since 2019 has been Deputy General Director of GESTOCI, the state oil storage company. She is married to Employment Minister Adama Kamara. She has not publicly responded to the disclosures.",
    searchTerms: ["nina keita", "nina k"],
  },
  {
    slug: "sidi-tiemoko-toure",
    name: "Sidi Tiémoko Touré",
    title: "Chef de Cabinet to President Ouattara, Ivory Coast",
    countries: ["Ivory Coast", "Africa"],
    bio: "Sidi Tiémoko Touré served as Chef de Cabinet — chief of staff — to President Alassane Ouattara of Ivory Coast. He appears in Epstein's archive connected directly to the Ivory Coast political thread. In September 2013, Epstein emailed Israeli Defence Minister Ehud Barak with Touré's personal email address, describing him as \"chief of staff of Ouattara\" and arranging a meeting. The introduction was coordinated through Nina Keita. The meeting was part of broader efforts by Epstein and Barak to broker a mass surveillance deal between Israel and Ivory Coast, which culminated in a formal security agreement signed in 2014. He later served as Minister of Animal and Fishery Resources under Ouattara.",
    searchTerms: ["sidi", "sidi tiemoko", "sidi toure", "sidi tiémoko"],
  },
  {
    slug: "ghislaine-maxwell",
    name: "Ghislaine Maxwell",
    title: "Epstein associate, convicted sex trafficker",
    countries: ["Kenya", "Ethiopia", "Rwanda", "Africa"],
    bio: "Ghislaine Maxwell was Jeffrey Epstein's longtime companion and associate. She was convicted in 2021 of sex trafficking and related offences and is serving a 20-year federal prison sentence. She appears in Epstein's Africa-related archive in a small number of emails touching on Kenya safari travel, Ethiopia logistics, and a Rwanda scholarship forwarding. She corresponded under her own name and the alias 'Gmax'.",
    searchTerms: ["ghislaine maxwell", "ghislaine", "gmax"],
  },
  {
    slug: "terje-rod-larsen",
    name: "Terje Rød-Larsen",
    title: "Former UN Special Envoy; President, International Peace Institute",
    countries: ["Nigeria", "Somalia", "Sudan", "Egypt", "Mali", "Libya", "Senegal", "Africa"],
    bio: "Terje Rød-Larsen is a Norwegian diplomat best known for brokering the 1993 Oslo Accords between Israel and the PLO. From 2004 to 2020 he served as president of the International Peace Institute in New York, a think tank that received approximately $650,000 in donations from Epstein foundations. Rød-Larsen described Epstein as \"my best friend.\" He took a personal loan of $130,000 from Epstein in 2013, and Epstein's 2019 will bequeathed $5 million each to his two children. He resigned from the IPI in 2020 after the financial ties became public. In the Epstein archive's Africa emails, Rød-Larsen appears routing Nigeria and Somalia security intelligence briefings through Epstein, including a report on the shooting of a Somali polio worker. As of 2026 he is under criminal investigation by Norway's economic crimes authority Okokrim.",
    searchTerms: ["terje rod-larsen", "terje", "rod-larsen", "ipinst"],
  },
  {
    slug: "sarah-kellen",
    name: "Sarah Kellen",
    title: "Personal Assistant to Jeffrey Epstein",
    countries: ["Kenya", "Nigeria", "Ivory Coast", "Senegal", "Gabon", "Mali", "Morocco", "Tanzania", "Uganda", "Africa"],
    bio: "Sarah Kellen served as Jeffrey Epstein's primary personal assistant and day-to-day scheduler. She was named as an unindicted co-conspirator in the 2007 Palm Beach investigation and received immunity under Epstein's 2008 non-prosecution agreement. A federal judge described her as a \"criminally responsible participant\" in Epstein's operation. She has never been criminally charged. In the Africa emails she appears coordinating Epstein's Africa tour itinerary, messaging Karim Wade on Epstein's behalf, and obtaining visas for Gabon, Sierra Leone, and Mali. She also used the alias Sarah Kensington professionally. She has stated through a spokesperson that she herself was a victim of Epstein's abuse.",
    searchTerms: ["sarah kellen", "sarah k", "kellen", "kensington"],
  },
  {
    slug: "karim-wade",
    name: "Karim Wade",
    title: "Former Minister of State, Senegal",
    countries: ["Senegal", "Africa"],
    bio: "Karim Wade is the son of Abdoulaye Wade, President of Senegal from 2000 to 2012. He served as Minister of State under his father and was widely expected to succeed him. Wade and Epstein first met in 2010 through Sultan Bin Sulayem. After his father's defeat, Karim Wade was arrested in 2013 and convicted of illicit enrichment in 2015, sentenced to six years in prison. Epstein became involved in efforts to secure his release, with emails indicating he sent $100,000 toward lobbying efforts. Nina Keita acted as intermediary during Wade's imprisonment. Wade was released in 2016 through a presidential pardon and subsequently went into exile in Qatar. He appears in over 100 emails in Epstein's archive across this period.",
    searchTerms: ["karim wade", "karim", "wade"],
  },
];

export function getPersonBySlug(slug) {
  return PEOPLE.find((p) => p.slug === slug) ?? null;
}
