export const STORIES = [
  {
    slug: "ivory-coast-surveillance",
    title: "How Epstein Brokered a Mass Surveillance Deal for Ivory Coast",
    summary:
      "Between 2011 and 2014, Epstein used his connections to President Ouattara's niece to help Israeli Defence Minister Ehud Barak sell a mass surveillance system to Ivory Coast.",
    countries: ["Ivory Coast"],
    date_range: "2011–2014",
    body: [
      "In December 2010, Ivory Coast was mid-civil war. Laurent Gbagbo had refused to concede after losing the election to Alassane Ouattara, and fighting was spreading across Abidjan. While that was unfolding, Karim Wade, son of Senegal's president and a regular Epstein correspondent, emailed Epstein to explain why he'd gone quiet: \"I am on the crisis on Ivory Coast.\" Epstein wrote back: \"I'm with Prince Andrew at my house in New York... we are talking about the opportunities in Africa.\" Prince Andrew was in the room.",
      "Ouattara won the war in April 2011, with UN and French forces arresting Gbagbo. Epstein was already booking his Africa trip. Flight records in the archive show the routing: Newark → Azores → Dakar → Bamako → Niamey → Benin City → Libreville, continuing toward Abidjan. That same month Nina Keita, Ouattara's niece, a former model who had been on Epstein's jet since at least 2002, wrote asking for \"more details concerning your trip to Abidjan.\"",
      "In November 2011, Epstein's team began preparing for the trip in earnest. Lesley Groff sent CDC vaccination guidance for Ivory Coast. An assistant wrote: \"I did. Do you think it's what he wants? I was a bit scared of him today.\" In January 2012, Epstein landed in Abidjan. A forwarded email describes his schedule: \"He is scheduled with the president at 4pm then minister of economy and finance at 6:30pm. Dinner at 8:30 with minister of interior. Wednesday he meets with the director of bureau of commerce and industry at 10, then CEO of the port at 12 with a tour of the port. Lunch with General Coulibaly around 2pm.\" Amadou Gon Coulibaly would later become Prime Minister.",
      "The meetings didn't stay in Abidjan. In June 2012, Ouattara flew to Jerusalem and met Ehud Barak, then Israel's Defence Minister, and Netanyahu. Epstein had been seeing Barak regularly for years. In September 2013 he sent Barak the personal email of Sidi Tiémoko Touré, Ouattara's chief of staff: \"chief of staff of outara, he arrives tomorw, try to coordianate.\" Keita had made the connection.",
      "A mass surveillance contract followed: Ivory Coast's phone and internet communications, built by former Israeli intelligence officials, formalised in 2014. Ouattara has since banned protests and imprisoned opponents. The emails don't establish a link between the surveillance system and those crackdowns.",
    ],
    email_ids: [
      "vol00009-efta00633187-pdf-1",
      "EFTA01805243-0",
      "EFTA01866037-0",
      "EFTA01993169-0",
      "EFTA01795507-0",
      "EFTA01740736-0",
      "EFTA01990469-0",
      "vol00009-efta00926086-pdf-2",
    ],
    news_links: [
      {
        title: "Did Epstein help Israel push for a security deal with Ivory Coast?",
        url: "https://www.aljazeera.com/news/2026/2/27/did-epstein-help-israel-push-for-a-security-deal-with-ivory-coast",
        source: "Al Jazeera",
      },
      {
        title: "Jeffrey Epstein Helped Israel Sell a Surveillance State to Côte d'Ivoire",
        url: "https://www.dropsitenews.com/p/jeffrey-epstein-israel-surveillance-state-cote-d-ivoire-ehud-barak-leaked-emails",
        source: "Drop Site News",
      },
      {
        title: "Quand Jeffrey Epstein vendait la Côte d'Ivoire à l'espionnage israélien",
        url: "https://akramkhariefmenadefense.substack.com/p/quand-jeffrey-epstein-vendait-la",
        source: "Akram Kharief / Substack",
      },
      {
        title: "Affaire Epstein : le PDCI-RDA demande des explications au gouvernement ivoirien",
        url: "https://www.pulse.ci/article/affaire-epstein-le-pdci-rda-demande-des-explications-au-gouvernement-ivoirien-et-exige-la-transparence-2026021801422117419",
        source: "Pulse Côte d'Ivoire",
      },
    ],
  },
  {
    slug: "libya-sovereign-wealth",
    title: "Epstein, Prince Andrew, and the Race to Control Libya's Billions",
    summary:
      "In October 2010, Epstein emailed a royal aide about flying to Tripoli with Prince Andrew to access Gaddafi's billions. Nine months later Gaddafi was dead, and a new intermediary was pitching Epstein on the same prize, now frozen in Western banks.",
    countries: ["Libya"],
    date_range: "2010–2013",
    body: [
      "In October 2010, Epstein emailed a royal aide: \"i want to go to tripoli lets organize with pa.\" PA was Prince Andrew, then Britain's trade envoy. The aide replied the next day: \"Spoke to PA. Tripoli can be organised, he wants more details.\"",
      "Epstein's pitch was straightforward. Gaddafi didn't know \"where to put his money.\" Epstein thought he could manage it. Andrew had met Gaddafi during official visits and referred to him in emails as \"Brother Leader.\" He had contacts. A few weeks later Andrew wrote to Epstein directly: \"I will call you later this evening after I have had my chat with my Libyan contact to see what we can arrange for you in Tripoli.\" Hours later: \"Libya fixed. Call me whenever.\"",
      "Epstein never flew to Tripoli. But the Libya thread didn't close. It ran in parallel. Separately, Andrew and a UAE-based investment banker named Terence Allen were discussing an $8 billion cash-for-oil deal involving Libya and Dubai. Andrew forwarded the entire exchange to Epstein. The banker suggested Andrew \"need not be involved officially\", that it could be arranged \"quietly and discreetly\" if Andrew provided a reference.",
      "Nine months later, Gaddafi was dead. His government had collapsed under NATO-backed rebel forces in the summer of 2011. By June 30, Gregory Brown, Chairman of GlobalCast Partners LLC, was in Epstein's inbox with a new proposition: get to the Transitional National Council before anyone else. Libya had roughly $80 billion in state funds frozen internationally, $32.4 billion of it in the US. Brown estimated the real total, including misappropriated assets, was three to four times that.",
      "The pitch had a structure. Asset recovery on contingency: Epstein's network takes 10 to 25 percent of whatever comes back. Former MI6 and Mossad operatives were \"willing to assist\" in tracing the funds. Brown invited Epstein to fly to Benghazi with him. July 16: \"you and I could end up being their go-to guys and make hundreds of millions if not billions in the process.\" Epstein had already replied: \"it is never simple.\" Brown kept sending. Epstein kept responding, through the Paris Libya Summit in September 2011 and through Libya's first post-war election in August 2012.",
      "Whether any of this made it past email is not established by the documents. Epstein didn't go to Benghazi. The Libyan Investment Authority's assets are still frozen, still contested between rival governments.",
    ],
    email_ids: [
      "EFTA02685573-0",
      "vol00009-efta00913890-pdf",
      "EFTA01994452-0",
      "EFTA01861283-0",
      "EFTA01995819-0",
      "vol00009-efta00878464-pdf",
      "vol00009-efta00720472-pdf",
      "EFTA01853841-0",
      "vol00009-efta00940589-pdf",
    ],
    news_links: [
      {
        title: "Epstein email reveals plan to access Libya's frozen state assets",
        url: "https://www.aljazeera.com/news/2026/2/1/epstein-email-reveals-plan-to-access-libyas-frozen-state-assets",
        source: "Al Jazeera",
      },
      {
        title: "Exclusive: Former Prince Andrew tried to facilitate Epstein-Gaddafi meeting",
        url: "https://www.channel4.com/news/exclusive-former-prince-andrew-tried-to-facilitate-epstein-gaddafi-meeting",
        source: "Channel 4",
      },
      {
        title: "Jeffrey Epstein planned to 'loot' Libya's frozen funds with complicity of international networks",
        url: "https://www.euronews.com/2026/02/02/jeffrey-epstein-planned-to-loot-libyas-frozen-funds-with-the-complicity-of-international-i",
        source: "Euronews",
      },
    ],
  },
  {
    slug: "wade-introduction",
    title: "How Sultan Bin Sulayem Brought Karim Wade to Epstein",
    summary:
      "In November 2010, Sultan Bin Sulayem brokered a meeting between Epstein and Karim Wade, son of Senegal's president. Within 48 hours Epstein was pitching an offshore digital economy for Senegal.",
    countries: ["Senegal"],
    date_range: "2010",
    body: [
      "November 13, 2010. A cold email arrives at Epstein's office. Karim Wade, son of Senegal's president and minister controlling 46% of the state budget, introduces himself. Sultan Bin Sulayem of Dubai World had asked him to make contact. Epstein's assistant replied within hours: apartment address, gate code, Monday at 5:30pm.",
      "Two days later Wade wrote again: \"I was very happy to meet you. Have no doubt that we will have fun.\" Epstein was already on a flight back. He replied mid-air with a pitch for Senegal: make it a banking centre and internet server hub, use technology five to ten years ahead of what exists now, internet gambling, hosting servers so companies can operate \"in Senegal without actually being there,\" mobile phone as bank account, nuclear power. He'd already spoken to \"the Gates group\" about it.",
      "It was a sales meeting disguised as a first conversation. Wade had just become one of the most powerful men in Senegal. Epstein wanted to be indispensable before anyone else arrived.",
      "Sultan's role in this is explicit in the emails. He didn't just know both men. He brokered the introduction deliberately. The same man sending Epstein photos with Dangote and African heads of state, forwarding Somaliland recognition documents, running Nigeria port deals. Sultan was also quietly routing Epstein into Senegal's political succession.",
    ],
    email_ids: [
      "EFTA02318552-1",
      "vol00009-efta00559607-pdf",
      "EFTA02416717-0",
      "EFTA01980734-0",
      "vol00009-efta00899072-pdf-1",
    ],
    news_links: [
      {
        title: "Epstein files reveal links to cash, women, power in Africa",
        url: "https://www.yahoo.com/news/articles/epstein-files-reveal-links-cash-025719741.html",
        source: "AFP / Yahoo News",
      },
    ],
  },
  {
    slug: "wade-beijing",
    title: "From Dakar to Beijing: How Epstein Triangulated Wade into China",
    summary:
      "Six months after Sultan brokered the Wade introduction, Epstein connected Senegal's power heir with Chinese billionaire Desmond Shum, then flew to Beijing himself to close the loop.",
    countries: ["Senegal"],
    date_range: "2011",
    body: [
      "Six months after Sultan Bin Sulayem made the introduction, Karim Wade was no longer just an Epstein contact. He was an asset being routed into a second network entirely.",
      "April 26, 2011. Epstein sent a two-line email: \"desmond, meet karem. karem, meet desmond.\" Desmond Shum was a Chinese billionaire whose connections ran through the upper reaches of the Communist Party. His memoir Red Roulette, published a decade later, would expose just how deep those ties went. He was based in Beijing. Wade was in Dakar, theoretically. Shum immediately offered to fly to Shanghai to meet him.",
      "Ten days later Epstein himself was heading to Beijing: arriving Monday, staying through Friday, back through Paris. He forwarded Shum's contact details directly to Wade. The Africa introduction had become a China introduction.",
      "What exactly was being discussed isn't spelled out in the emails. Offshore banking appears in the context. Epstein had been pitching Wade on financial infrastructure for Senegal since their first meeting in November 2010. Shum had the relationships in Beijing that could make something like that real. Wade had the political access in Dakar. Epstein was in the middle, connecting both.",
      "The DOJ documents confirm Shum and Wade met in Beijing on May 9, 2011. What came of that meeting isn't in the archive.",
    ],
    email_ids: [
      "EFTA02538527-0",
      "EFTA01865779-0",
      "EFTA01809435-0",
    ],
    news_links: [
      {
        title: "Epstein files reveal links to cash, women, power in Africa",
        url: "https://www.yahoo.com/news/articles/epstein-files-reveal-links-cash-025719741.html",
        source: "AFP / Yahoo News",
      },
    ],
  },
  {
    slug: "harem-marrakech",
    title: "The Harem Part: Karim Wade's Offer to Epstein",
    summary:
      "In November 2011, Karim Wade, son of Senegal's president, offered to manage a harem in Epstein's planned Moroccan palace. Epstein replied he wanted 'a separate house for the women' and was copying Prince Bandar bin Sultan's Marrakech palace plans.",
    countries: ["Morocco"],
    date_range: "2011",
    body: [
      "November 11, 2011. Epstein emails a contact: \"perfect.. I will leave time. also free in the evening. Im working on moroccan house plans.\" The reply comes the next morning from an account logged as \"afri xp\": \"Do not forget in the house the harem part. Happy to manage it...\"",
      "Epstein wrote back: \"eunuchs only. I want it to have a separate house for the women. I am getting the house plans of Bandar in Marrakech.\"",
      "Bandar is Prince Bandar bin Sultan, Saudi Arabia's former ambassador to the US and former director of Saudi intelligence. Epstein wasn't sketching a holiday villa. He was copying a Saudi prince's palace.",
      "The identity of \"afri xp\" is confirmed by the documents. Six months earlier, on May 22, 2011, the same account had emailed Epstein asking him to switch to a new private address. Epstein replied: \"im sorry, who is this.\" The response: \"This is Karim sorry better use this email adr. Cu. Karim.\" The account resolves to afrixp@hotmail.com. \"Afri xp\" is Karim Wade, son of Senegal's president, the man Sultan Bin Sulayem had introduced to Epstein in November 2010.",
      "The harem email doesn't appear in the Africa-filtered dataset. No country keywords triggered it. It surfaced only through a direct quote search of the full 1.7 million email archive. What the documents show is the offer, the confirmation of who made it, and the answer.",
    ],
    email_ids: ["EFTA01852132", "EFTA01864579-0", "EFTA01864579-2"],
    news_links: [
      {
        title: "Epstein Made Efforts to Free the Son of Senegal's Former President After Corruption Conviction",
        url: "https://www.occrp.org/en/scoop/epstein-made-efforts-to-free-the-son-of-senegals-former-president-after-corruption-conviction",
        source: "OCCRP",
      },
    ],
  },
  {
    slug: "senegal-banking-investor-meeting",
    title: "The Senegal Banking Project: Epstein, Sultan, Gates, and Karim Wade",
    summary:
      "In the summer of 2011, Epstein coordinated an investor meeting for Karim Wade's Senegal banking project, with Sultan Bin Sulayem lined up to attend, JPMorgan consulted on high-frequency trading infrastructure, and the Gates Foundation sending a team for municipal finance.",
    countries: ["Senegal"],
    date_range: "2011",
    body: [
      "The pitch started the night they met. November 15, 2010. Wade had just left Epstein's apartment. Epstein was already on his flight home, typing out ideas for Senegal: internet banking, server infrastructure, mobile-phone-as-bank-account, high-frequency trading, nuclear power. \"I have spoken to the Gates group about it.\" Wade had been in the room for a few hours.",
      "By May 2011 it had moved past ideas. Epstein told Wade he'd spoken to JPMorgan. They thought high-frequency trading infrastructure should be part of the bank. Wade asked who JPM was. Epstein pointed him to Infinium, a Chicago HFT firm. Wade called it \"a huge competitive advantage\" and asked for technical details. He was a cabinet minister controlling 46% of Senegal's state budget. He didn't know the JPMorgan abbreviation.",
      "June 13: \"Gates now wants to send a team to you to organize municipal finance for poor related projects.\" Same email: \"I really appreciate our new friendship. There is so much to do.\" Epstein had known Wade seven months.",
      "The investor meeting came together in late August. Epstein had been trying to line it up since May: \"my wash friends will be in Paris on 28–30.\" On August 25 he checked in directly: \"question re african bank — if you have changed your mind, its ok, but it would be helpful if I knew.\" They settled on Monday at 5pm at Epstein's Paris place. The Washington friends were almost certainly the JPMorgan contacts. Rasseck Bourgi, a key intermediary between Paris and Francophone African political networks and the brother of Robert Bourgi, the Gaullist Africa fixer, was Wade's man on the ground.",
      "Sultan came to New Mexico in July. Epstein called Wade while Sultan was there. Wade: \"Miss u guys.\" By August, Epstein was in Dubai with Sultan for Ramadan, then Saudi Arabia. He wanted to wait on that trip until Wade could come.",
      "The Senegal bank never materialised. Wade's father lost the election in March 2012. Wade himself was arrested thirteen months later. What the emails document is the year before that: JPMorgan for trading infrastructure, Gates for the development angle, Sultan as the Gulf anchor, Wade as the political vehicle. Epstein in the middle, building something that didn't survive the election.",
    ],
    email_ids: [
      "EFTA01865356",
      "EFTA01864665-0",
      "EFTA01864665-1",
      "EFTA01863799",
      "EFTA01776670-0",
      "EFTA01776670-1",
      "EFTA01776385-0",
      "EFTA01776385-1",
    ],
    news_links: [
      {
        title: "Epstein files reveal links to cash, women, power in Africa",
        url: "https://www.yahoo.com/news/articles/epstein-files-reveal-links-cash-025719741.html",
        source: "AFP / Yahoo News",
      },
      {
        title: "Epstein Made Efforts to Free the Son of Senegal's Former President After Corruption Conviction",
        url: "https://www.occrp.org/en/scoop/epstein-made-efforts-to-free-the-son-of-senegals-former-president-after-corruption-conviction",
        source: "OCCRP",
      },
      {
        title: "Lobbying diplomatique autour de Karim Wade",
        url: "https://senego.com/moyennant-finances-et-lobbying-diplomatique-des-correspondances-devoilent-lintrusion-inattendue-de-jeffrey-epstein-dans-une-affaire-judiciaire-majeure-a-dakar_1920486.html",
        source: "Senego",
      },
      {
        title: "Epstein to Karim Wade, June 2011: \"Gates now wants to send a team to you to organize municipal finance\"",
        url: "/emails/EFTA01863799-0",
        source: "DOJ email archive",
      },
    ],
  },
  {
    slug: "wade-prison-access",
    title: "Operation Saving Soldier Wade: How Epstein Got Inside Rebeuss Prison",
    summary:
      "After Karim Wade's arrest in 2013, Epstein coordinated prison access through Nina Keita, brokered by Paris fixer Rasseck Bourgi, and began paying Wade's defense lawyers through a Moroccan bank routing.",
    countries: ["Senegal"],
    date_range: "2013–2014",
    body: [
      "Karim Wade was arrested April 15, 2013. By August he was in Rebeuss, Dakar's main detention facility, facing charges of illicitly accumulating $240 million. Epstein's first move was to find a way in.",
      "He didn't contact the prison. He called Rasseck Bourgi, who appears in the emails as \"Ute Bourgi.\" Bourgi was the brother of Robert Bourgi, the French lawyer who spent decades as the quiet back-channel between successive French governments and Francophone African leaders. Rasseck had his own connections in Dakar. Epstein's request was simple: Nina Keita, Ouattara's niece, wants to visit Wade. Can she?",
      "Rasseck came back with the procedure. She needed authorization from the judge. The lawyers to contact were Maître Seydou Diagne or Maître Demba Bathily. Epstein forwarded it to Nina. She replied the next morning: \"Thank you Jeffrey!! I'll contact them tomorrow.\"",
      "Five months later Epstein was talking to Diagne directly. A short exchange: \"karim asked that we connect.\" They moved to Viber. By May 2014, Diagne sent his bank details: Attijariwafa Bank, Dakar branch, routing through Casablanca. Epstein told Nina he'd sent the transfer twice. Diagne confirmed receipt with a voucher. Wade's prison assistant came back asking if Epstein could send another payment. The lawyers needed more.",
      "Epstein had known Wade for less than three years. He had introduced him to JPMorgan, the Gates Foundation, Sultan Bin Sulayem, and Ehud Barak. He was now paying his criminal defense lawyers through a Moroccan bank routing, coordinated through an Ivorian presidential niece, brokered by a Paris fixer with ties to the Élysée.",
    ],
    email_ids: [
      "vol00009-efta00966541-pdf-2",
      "EFTA01963508-0",
      "EFTA01945668-0",
      "EFTA01927653-0",
      "EFTA01924121-0",
      "EFTA02705431-0",
    ],
    news_links: [
      {
        title: "Epstein Made Efforts to Free the Son of Senegal's Former President",
        url: "https://www.occrp.org/en/scoop/epstein-made-efforts-to-free-the-son-of-senegals-former-president-after-corruption-conviction",
        source: "OCCRP",
      },
    ],
  },
  {
    slug: "wade-dc-lobbying",
    title: "The DC Machine Epstein Built to Free Karim Wade",
    summary:
      "From October 2015, Epstein funded a five-track Washington lobbying campaign covering State Department pressure, Congressional briefings, a planted op-ed, Amnesty International outreach, and a human rights report target, until Wade walked out of prison in June 2016.",
    countries: ["Senegal"],
    date_range: "2015–2016",
    body: [
      "In October 2015, Nelson Mullins, a Washington DC lobbying firm, received an approach. An internal memo recorded it this way: \"We were contacted by one of Mr. Wade's business associates in the U.S. who happens to be old friends with Bob Crowe. He said he would handle the payment details and contract.\" The associate was Epstein. The contract was $50,000. The job was to get Karim Wade out of Rebeuss prison.",
      "By December, Crowe was chasing the retainer: \"We did not get the $50,000 promised by 11-30.\" Wire instructions followed in January 2016. Epstein paid.",
      "What that $50,000 bought was a five-track pressure campaign running simultaneously in Washington.",
      "At the State Department, Crowe met contacts directly. April 2016: \"good meeting at State... working behind the scenes to put pressure on Macky Sall.\" The US Ambassador to Senegal was identified as a lever. On Capitol Hill, lobbyist Vinoda Basnayake briefed Yebbie Watkins, chief of staff to House Democratic Whip Jim Clyburn, on the case. A Ron Dellums op-ed was placed in The Hill. Crowe's note on it: keep it \"highly confidential.\" Dellums was a former chairman of the House Armed Services Committee. His name carried weight on African affairs. Amnesty International was approached to take up Wade's detention as a human rights case. And the State Department's FY17 human rights report on Senegal was identified as a specific target: get Wade's name in as a political prisoner.",
      "The campaign tracked Macky Sall's own vulnerabilities as leverage. February 2016, Crowe to Epstein: \"We feel that the development of Macky extending his term limits from 5 to 7 years helps us.\" Sall's political exposure was being used as pressure.",
      "June 16, 2016. Crowe: \"He has told my friends high up at State that he was going to do it. They have been putting pressure on him!\" Eight days later Wade walked out of Rebeuss. He was on a plane to Doha the same night.",
    ],
    email_ids: [
      "vol00009-efta00838871-pdf-5",
      "vol00009-efta00707609-pdf",
      "vol00009-efta00698508-pdf-2",
      "EFTA02394840-0",
      "EFTA01742150-0",
      "EFTA02459411-0",
      "EFTA02339435-0",
    ],
    news_links: [
      {
        title: "Epstein Made Efforts to Free the Son of Senegal's Former President",
        url: "https://www.occrp.org/en/scoop/epstein-made-efforts-to-free-the-son-of-senegals-former-president-after-corruption-conviction",
        source: "OCCRP",
      },
      {
        title: "Lobbying diplomatique autour de Karim Wade",
        url: "https://senego.com/moyennant-finances-et-lobbying-diplomatique-des-correspondances-devoilent-lintrusion-inattendue-de-jeffrey-epstein-dans-une-affaire-judiciaire-majeure-a-dakar_1920486.html",
        source: "Senego",
      },
      {
        title: "Epstein files reveal links to cash, women, power in Africa",
        url: "https://www.yahoo.com/news/articles/epstein-files-reveal-links-cash-025719741.html",
        source: "AFP",
      },
    ],
  },
  {
    slug: "wade-qatar-exile",
    title: "From Rebeuss to Doha: Epstein Was Still Pitching Wade the Day He Died",
    summary:
      "Hours after walking out of prison in June 2016, Karim Wade was on a plane to Qatar. Within weeks he and Epstein had revived the Norwegian LNG deal. Epstein was still pitching him to investors in 2018.",
    countries: ["Senegal"],
    date_range: "2016–2018",
    body: [
      "June 25, 2016. Sultan emailed Epstein with the official version: Wade had been granted a presidential pardon, though he remained liable for a $200 million fine. French media and Al Jazeera were reporting that Qatar had acted as mediator. He was flown to Doha the same night he walked out.",
      "Two months later, first contact from exile. Epstein: \"Any fun?\" Wade: \"Yes Sir, really enjoy Qatar.\"",
      "By September he was already back to business. \"Yes still in Doha. Are u still in contact with ur LNG friend?\" The LNG friend was Morits Skaugen, owner of Norway's largest LNG fleet, whom Epstein had introduced to Wade in July 2012, a year before the arrest. Epstein confirmed: \"you mean moritz the lng norwegian?\" Wade: \"Yep the norwegian guy with the fleet of LNG ships.\" Four years in prison. First week of real contact. Back to the Norwegian LNG deal.",
      "November 2: Epstein was flying to Qatar. Wade confirmed he'd be there: \"Just met with J'aborde who told me that you are coming.\" J'aborde is an unidentified contact who already knew Epstein was en route. Wade had a network running in Doha.",
      "November 29: Epstein pitching Wade to a new contact, identity unconfirmed in the documents: \"Karim Wade is the son of the president of Senegal (they just found GAS offshore). He was put in jail to remove him from running against the current president. He is in Qatar awaiting his political return to power which is almost guaranteed. He is the most charismatic and rational of all the Africans.\"",
      "Epstein died in August 2019. The last Wade emails in the archive are from 2018, still in Doha, still in contact. Wade did return to Senegal eventually, running for president in 2024. He lost. The gas is still offshore.",
    ],
    email_ids: [
      "EFTA02339435-0",
      "vol00009-efta00820017-pdf",
      "EFTA01744455-0",
      "vol00009-efta00817072-pdf",
      "EFTA01738729-0",
      "vol00009-efta01060422-pdf-1",
    ],
    news_links: [
      {
        title: "Epstein Made Efforts to Free the Son of Senegal's Former President",
        url: "https://www.occrp.org/en/scoop/epstein-made-efforts-to-free-the-son-of-senegals-former-president-after-corruption-conviction",
        source: "OCCRP",
      },
      {
        title: "Epstein files reveal links to cash, women, power in Africa",
        url: "https://www.yahoo.com/news/articles/epstein-files-reveal-links-cash-025719741.html",
        source: "AFP",
      },
    ],
  },
  {
    slug: "sultan-scouting-operation",
    title: "Sultan's Scouting Operation: How Epstein Mapped a Continent",
    summary:
      "Between 2012 and 2013, Sultan Bin Sulayem moved through Africa and Central Asia, Angola, Gabon, Congo, Kazakhstan, briefing Epstein from helicopters and energy summits while Epstein identified the financial angles and asked who to call.",
    countries: ["Angola", "Gabon", "Ivory Coast"],
    date_range: "2012–2013",
    body: [
      "By mid-2012 the network had a method. Sultan Bin Sulayem would move first, through state visits, energy summits, and presidential meetings, then brief Epstein afterward. Epstein would identify the financial angle and ask who to call.",
      "July 2012: Sultan to Epstein, planning an October trip: Angola, Gabon, Ivory Coast. Epstein's response was immediate: \"I can set up Standard Bank and you for Ivory Coast, check if the IC government is interested in the service.\" He already had the Standard Bank contact. He was proposing to sell a financial service to a government he'd never visited, through a man who was planning to be there in three months.",
      "October 2012: Sultan hosted a Dubai energy summit. The guest list was a map of where Epstein wanted to be: presidents of Rwanda, Gabon, and Djibouti attended. Sultan was building the relationships. Epstein was watching the list.",
      "November 2, 2012. Wade from Angola: \"Angola is a big target for our project. Meeting with my friend the daughter of the PR 3rd week of november. If ur around Paris or London, I can introduce u to her.\" The daughter of the PR, President dos Santos, was Isabel dos Santos, then Africa's wealthiest woman and her father's designated heir to Angola's state energy sector. Three days later Epstein to Wade: \"will dos cantos be in paris on the 29th?\" Wade offered to introduce Epstein to Isabel dos Santos in November 2012. Epstein asked if she'd be in Paris on the 29th. Nothing in the archive confirms any meeting took place.",
      "By March 2013, Sultan had a new Africa trip planned, South Africa, Angola, Zambia, Ethiopia, with Sheikh Abdullah, a Gulf royal. He was in contact with Ali Bongo in Gabon, met President Kabila in Congo Kinshasa, and was referencing an \"American fund manager\" for the next visit. The American fund manager was Epstein.",
      "May 11, 2013. Sultan emailed Epstein from a helicopter. He was flying over Kazakhstan with the country's president, watching the inauguration of a China-CIS rail link. He was briefing Epstein on a $400 billion Chinese industrial city deal being built on the Kazakhstan-China border. Epstein replied: \"I will be with Bill Gates Paris, 9-10 June then free.\"",
      "The same man. One week: Kazakhstan by helicopter with a Central Asian president. The next: Paris with Bill Gates.",
    ],
    email_ids: [
      "EFTA01876197",
      "EFTA02379031",
      "EFTA01765205",
      "EFTA01978629",
      "EFTA01976871",
      "vol00009-efta01143801-pdf",
      "EFTA01759560",
      "EFTA01975989",
      "EFTA01975812",
    ],
    news_links: [],
  },
  {
    slug: "nigeria-ports-deal",
    title: "The Nigeria Ports Deal: Sultan, Zeitlin, and Epstein's Room",
    summary:
      "In June 2018, Epstein brokered negotiations between DP World chairman Sultan Bin Sulayem and Nigeria sovereign wealth fund chair Jide Zeitlin, cycling through Obama's White House Counsel and the Emir of Kano as social proof when the deal stalled.",
    countries: ["Nigeria"],
    date_range: "2018",
    body: [
      "The deal started a month earlier than the emails suggest. May 3, 2018: President Buhari was at the White House meeting Trump. Sultan Bin Sulayem was also in Washington that day. Zeitlin tried to arrange a face-to-face but Sultan left for Cyprus before it could happen. That evening, Nigeria's trade minister Okey Enelamah stopped by Zeitlin's home, fresh from the Buhari/Trump summit. He mentioned his discussions with Sultan at Davos. Zeitlin also noted he'd spoken with Vice President Pence earlier that day. He forwarded all of it to Epstein: \"No worry both problem and solution will still be there.\"",
      "The next morning Zeitlin had another question for Epstein: \"do you know Oleg Deripaska or Ivan Glasenberg?\" Deripaska was the sanctioned Russian aluminum oligarch. Glasenberg was the CEO of Glencore, the world's largest commodity trader, with operations across Nigeria and central Africa. Epstein replied: \"Easy. Does 11 work.\" The Nigeria ports conversation and the Russian/commodity access conversation were happening in the same exchange, one day apart.",
      "June 5, 2018. Sultan Bin Sulayem emailed Jide Zeitlin, Goldman partner, chair of Nigeria's sovereign wealth fund, just back from Abuja: \"Jeffrey introduced us a while ago. We are very interested in Nigeria.\" He laid out two targets: Badagry, where Maersk had signed three years earlier but never broken ground, and Lekki, already given to an Indian company a decade ago. He wanted Bolloré's portfolio. He wanted a proposal.",
      "Zeitlin didn't give him one. \"I am recently back from Abuja and Paris. We should meet.\" Sultan replied with thirteen years of context. DP World had been trying to enter Nigerian ports since 2005. He'd met the previous two presidents. He'd met the current Lagos governor. Every attempt had collapsed: dollar dividends versus naira earnings, an industrial park offer he'd declined because \"there is no benefit for us to create an industrial zone to produce cargo for someone else's port.\" His position was clear: greenfield at Badagry or brownfield acquisition in Lagos. Nothing else.",
      "Zeitlin wrote back to Sultan, then forwarded the thread to Epstein with a different message: \"Your pal does not get it. I am not a shopkeeper in a souk or on Old Bond Street trying to sell him a trinket. His 'give me a proposal approach' doesn't work in Nigeria. I need to get a better sense of him, his team, and their long-term objectives. Once I better understand him, I will then determine if I want to work with him. I am not simply for sale.\"",
      "Epstein's first card, June 8: \"you do know that kathy ruemmler is my close buddy.\" Kathy Ruemmler was Barack Obama's White House Counsel. Sultan: \"Who do you not know!\" Epstein's second card, June 9: \"emir of kano.\" Muhammad Sanusi II, former Central Bank Governor of Nigeria, Emir of Kano, one of the most powerful traditional rulers in the country. When the deal stalled, Epstein cycled through his rolodex. Obama's counsel. Then northern Nigeria's most influential figure. He wasn't providing capital or expertise. He was proving he could open any room.",
      "Zeitlin wrote back to Epstein, not Sultan: \"this back and forth has value as part of learning about Sultan. How his brain is wired. Why he has struggled to get things done on the continent.\" Then: \"unbeknownst to Sultan, I was otherwise looking at being in Abu Dhabi this coming Sunday and Monday — related to our mutual friend.\" The mutual friend is unnamed. Zeitlin was running a separate Abu Dhabi track simultaneously, connected to someone both he and Epstein knew, while telling Sultan he was still evaluating the relationship.",
      "The deal didn't close. DP World visited Nigeria in March 2019 and proposed industrial parks, the same offer Sultan had rejected in January 2018. Never approved.",
      "What the emails show is the structure: Zeitlin as the access into Nigerian government, Sultan as the capital, Epstein as the room they both passed through. Not a broker in any formal sense. Just the person without whom the meeting doesn't happen.",
      "Three months later, Djibouti nationalized DP World's main East Africa hub. Zeitlin wrote to Epstein: \"I hope your pal's sojourn in Tel Aviv was more effective than his efforts on the African continent.\" The Nigeria deal never closed. Sultan Ahmed bin Sulayem resigned as DP World chairman on February 13, 2026, five days after the Epstein files became public. DP World acquired a controlling stake in a Nigerian logistics provider in 2022 and began expanding in Lagos.",
    ],
    email_ids: [
      "EFTA02449325-0",
      "EFTA02447106-0",
      "vol00009-efta00815378-pdf",
      "vol00009-efta00816624-pdf",
      "EFTA01975675-0",
      "EFTA01975388-0",
      "EFTA01975232-0",
      "EFTA01974891-0",
      "EFTA01974654-0",
      "vol00009-efta01038618-pdf",
      "vol00009-efta01039400-pdf",
    ],
    news_links: [
      {
        title: "Epstein Flipped Israel's Gaza-Tested Biometric Scanners Into Nigeria Ports Deal for UAE",
        url: "https://www.dropsitenews.com/p/epstein-ehud-barak-sultan-sulayem-nigeria-ports-israel-dp-world",
        source: "Drop Site News",
      },
      {
        title: "Badagry Deep Seaport Developer Sultan bin Sulayem Resigns Amid Jeffrey Epstein Revelations",
        url: "https://www.newspeddlers.com/2026/02/badagry-deep-seaport-developer-sultan.html",
        source: "News Peddlers",
      },
    ],
  },
  {
    slug: "kenya-safari-2009",
    title: "The Kenya Safari: What Epstein Asked of Miasha Fisher Before She Left",
    summary:
      "In 2009, Epstein and Peggy Siegal planned a Kenya safari for 21-year-old Miasha Fisher. Ghislaine Maxwell reviewed the full visa and itinerary package and asked what 'the work portion' was. The documents don't answer that question.",
    countries: ["Kenya"],
    date_range: "2009",
    body: [
      "April 9, 2009. Paula, Miasha Fisher's mother, sent Epstein photos of a performer called TORA, asking him to pass them to someone named Tommy. Epstein replied: \"Put Miasha in a sexy outfit and meet Tommy.\" The next day, more specific: \"white button down shirt with white bra if miasha has it - hair - ponytail see you soon.\" Miasha Fisher was 21 years old.",
      "Peggy Siegal launched the Kenya plan on April 17: an \"African Equestrian safari and internship\" for her daughter Mattie and Miasha. Three days later Epstein made first direct contact with Miasha: \"call.\" Then: \"you should record your current voice and take photos of your current physique.\"",
      "April 27, Epstein to Peggy about Paula: \"treat her like you would any other client.. 10k per month for six months? your call.\"",
      "May 28: the trip was fully documented. Epstein capped the gift at $13,000 per person, exactly the IRS annual gift tax exclusion limit. He forwarded the full package to Ghislaine Maxwell: visa documents, itinerary, insurance. Maxwell replied the next morning: \"Wow..what is the work portion of this..it looks like a holiday camp..i am v jealous.\"",
      "June 11, Epstein to Miasha: \"have you started pills and shots?\" She confirmed. Epstein: \"great --- Israeli?\"",
      "Miasha didn't go. By late June Mattie had dropped out of the summer leg. The December trip that happened was Peggy's own. Mattie and CNN anchor Felicia Taylor, departing Amsterdam, Cottar's Camp in the Masai Mara, Sasaab, Lamu. Epstein's send-off: \"you will be amazed by the aroma.\"",
      "Maxwell asked what the work portion was. The documents don't answer that. Read individually, each exchange has an innocent explanation. Read in sequence: the outfit instructions, the physique photos, the gift structured to the legal limit, Maxwell reviewing the visa package, the medical clearance questions. They describe a preparation process.",
    ],
    email_ids: [
      "EFTA02412701",
      "EFTA01782176",
      "vol00009-efta00748701-pdf",
      "EFTA01827283",
      "EFTA01829651",
      "EFTA01829799",
      "vol00009-efta00749876-pdf",
      "EFTA02443081-0",
      "EFTA02443211-1",
    ],
    news_links: [],
  },
  {
    slug: "somaliland-recognition",
    title: "Somaliland: The Unrecognized State Sultan Wanted Epstein to Legitimize",
    summary:
      "Between 2011 and 2018, Epstein accumulated seven years of Somaliland interest, from a field scout's report out of Hargeisa, through water and oil pitches near Berbera, to Sultan Bin Sulayem firing a six-document recognition lobbying dossier at him in April 2018, two months before the Nigeria ports negotiations began.",
    countries: ["Somalia"],
    date_range: "2011–2018",
    body: [
      "November 2011. A contact named Melanie emailed Epstein from Amsterdam, just back from Somaliland: \"Is incredible. Somalia is a huge mess of a place but Somaliland is really smart and progressive. Zero money but tons of ingenuity. Impressive what they get done. Made the trip by land from north Ethiopia. Had a full military escort, AK 47s etc. Another world. Very safe. You should fly yourself to Hargeisa.\" Somaliland had declared independence from Somalia in 1991 after the collapse of the Barre regime. No UN member state had recognized it. It had its own currency, its own passport, its own elected government. It also had Berbera, a deep-water port on the Gulf of Aden, 150 miles from Yemen, positioned between the Suez Canal and the Indian Ocean.",
      "Five months later the commercial pitch arrived. April 2012: a redacted contact emailed Epstein about \"AfricEAU\", a water export company. The hook was Berbera. \"There are huge water reserves, untapped and clean, near port city of Berbera. Direct access to Saudi market. Easy to ship. Minimal transport. Again Somaliland.\" Epstein replied: \"I like it.\" The same week a Seattle-based contact, email handle mwalkermd, sent Epstein slide decks titled \"ZuniMu Somaliland\" and \"ZuniMu Ethiopia,\" nervous enough about the banking projections inside that he offered to fax rather than email them. The resource logic was consistent across both pitches: Berbera as export infrastructure, Saudi Arabia as the buyer, Somaliland's unrecognized status as a feature rather than a problem: fewer regulatory constraints, lower barriers to entry.",
      "June 2013. Epstein sent a short query to a redacted contact: \"somaliland, yemen, comoros island, are there any gates program there.\" The reply came back the same day: \"No.\" He was checking whether the Gates Foundation had established a presence he could work through, the way IPI's polio operation had given him leverage in Nigeria. There was no foothold. He noted it and moved on.",
      "August 2013. A contact who addressed Epstein as \"my dear cousin\", using the email chairman.shaherov@gmail.com, wrote from Somaliland: \"Finished alhamdulilah a good exploration concession for oil. Need 50 million towards three exploration blocks of about 30,000 kilometres area, good prospect. When my cousin coming to Europe.\" Epstein: \"end of sept.\" Then: \"fly to st bart, it is french i will meet you there.\" Shaher replied that a friend's wedding in Turkey was first, then he'd see. Nothing in the archive confirms the St. Barts meeting. The oil concession, three blocks across 30,000 square kilometres of Somaliland territory, is the largest single financial ask in the Somaliland thread. It also went nowhere documented.",
      "April 2, 2018. Sultan Bin Sulayem sent Epstein six documents in seven minutes. The subjects were numbered: \"1_ The recognition of Somaliland — a brief history.\" \"2_ achievements against all the odds.\" \"3_ in the interests of the world.\" \"4_ growing international engagement and support.\" \"6_ Q&A.\" And then the legal anchor: the original 1960 British treaty, CMND-1101, signed June 26 in Hargeisa. It formalized the independence of British Somaliland in the three days before it voluntarily united with Italian Somalia to form the Somali Republic. Sultan was making the historical argument: Somaliland had been an independent state with international legal standing. The 1991 declaration was a restoration, not a secession. This was not casual forwarding. It was a prepared dossier, structured for an audience.",
      "The audience was Epstein's Washington network. DP World had signed a 30-year concession for Berbera port in 2016, committing $442 million to expand it into a major regional hub. A recognized Somaliland would be a stable treaty counterparty. An unrecognized one was a commercial bet. Sultan sent the dossier two months before he opened the Nigeria ports negotiation with Jide Zeitlin. The same period, the same channel, two separate Africa plays in parallel. The emails don't show Epstein acting on the recognition documents.",
    ],
    email_ids: [
      "EFTA02011559",
      "EFTA02011692",
      "EFTA01885540",
      "EFTA01881890-0",
      "EFTA02571170-0",
      "vol00009-efta00962987-pdf-1",
      "EFTA01959738-0",
      "EFTA01959856",
      "EFTA01960507",
      "EFTA01962912",
      "vol00009-efta00842525-pdf",
      "vol00009-efta00842526-pdf",
      "vol00009-efta00842536-pdf",
      "vol00009-efta00842539-pdf",
      "vol00009-efta00842511-pdf",
      "vol00009-efta00842519-pdf",
    ],
    news_links: [],
  },
  {
    slug: "rod-larsen-epstein-intelligence",
    title: "Terje Rød-Larsen: The Diplomat Who Fed Epstein Intelligence",
    summary:
      "The architect of the Oslo Accords and President of the International Peace Institute was one of Epstein's closest contacts, visiting his island, brokering his meetings with Sultan, and using him as a relay channel to Bill Gates for UN field intelligence from Nigeria, Somalia, and Pakistan.",
    countries: ["Nigeria", "Somalia"],
    date_range: "2011–2015",
    body: [
      "On March 28, 2011, Terje Rød-Larsen sent Epstein a thank-you note: \"Thanks, Jeff, for a great day on a wonderful and totally unique place! We all loved it. Emma and Edward are ecstatic (think the four wheel drives made the strongest impression!). My mind is working on further ideas for creative development. Warmest Terje. Ps Mona blows a kiss.\" Emma and Edward were his children. Mona was his wife. The family had spent the day on Little Saint James. Rød-Larsen was the President of the International Peace Institute, the UN-affiliated think tank he had led since 2005. Before that, UN Special Envoy for Lebanon. Before that, the Norwegian diplomat who brokered the Oslo Accords.",
      "The friendship started in Dubai. January 2011: \"Back in NY. Thanks for lunch in Dubai! Was great. When are you back?\" By April he was asking Epstein: \"Do you want me to invite Sultan to breakfast on Sunday? Or would you prefer more private time?\" Sultan Bin Sulayem, chairman of DP World and Epstein's most active Africa operator, and Rød-Larsen were in the same city. Rød-Larsen was offering to put them in a room together. The man who spent his career mediating between heads of state was also managing Epstein's social calendar.",
      "IPI ran a field intelligence operation on polio eradication in conflict zones, Pakistan, Afghanistan, Nigeria, Somalia, through a researcher named Nasra Hassan. Her reports went to IPI's Vienna office, then to Rød-Larsen, then to Epstein. The Gates Foundation was the funder. By February 2015 the chain was explicit: Hassan sent Rød-Larsen a Pakistan update marked \"Urgent, Confi\" with the instruction \"plz pass on to Bill Gates.\" It went to Epstein first.",
      "Nigeria was the most active thread. November 2013: Boko Haram had attacked polio workers in Kano. A northern Nigerian group was calling on President Jonathan to suspend Gates's planned visit. Rød-Larsen forwarded the report to Epstein. December 2013: IPI researcher Mark Shaw sent a two-page intelligence brief, \"what we are hearing at multiple levels,\" about polio obstruction. It went to IPI director Andrea Pfanzelter, then Rød-Larsen, then Epstein. June 2014: IPI's formal reports on barriers to polio eradication in Nigeria and Somalia were forwarded to Epstein. Classified research on Nigerian security conditions, routed through a convicted sex offender to the world's largest private foundation.",
      "Other material moved through the same channel. August 2011: Rød-Larsen forwarded Epstein the UN Secretary-General's telephone conversation with Turkey's Foreign Minister, a document for internal UN circulation. July 2014: a Kazakhstan economic advisory document, mildly edited by Lawrence Summers, forwarded to Epstein. \"I've edited mildly what was sent below. Now good w me,\" Summers wrote. Rød-Larsen was also using Epstein to chase an outstanding payment dispute with media mogul Mort Zuckerman. He asked him to find out how much Zuckerman had paid \"to date.\" He was offering to fly to New York for dinner from the Cayman Islands.",
      "Rød-Larsen was removed as IPI president in 2021 after a New York Times investigation revealed a $130,000 personal loan from Epstein. As of 2026 he is under criminal investigation by Norway's economic crimes authority Okokrim. His children were named as beneficiaries in Epstein's will, $5 million each, in a document signed two days before Epstein's death.",
    ],
    email_ids: [
      "EFTA02025540",
      "vol00009-efta00690095-pdf",
      "EFTA01868773",
      "EFTA01755599-1",
      "EFTA01959363-1",
      "EFTA01947451-0",
      "vol00009-efta00990564-pdf",
      "vol00009-efta00864113-pdf",
      "EFTA01913108",
      "vol00009-efta00874786-pdf",
      "EFTA01950846",
    ],
    news_links: [
      {
        title: "Head of U.N.-Affiliated Research Group Resigns After Disclosing Epstein Payment",
        url: "https://www.nytimes.com/2021/08/12/us/politics/epstein-terje-rod-larsen-international-peace-institute.html",
        source: "New York Times",
      },
    ],
  },
];

export function getStoryBySlug(slug) {
  return STORIES.find((s) => s.slug === slug) ?? null;
}
