#!/usr/bin/env python3
"""
Export all manually inserted rows from the production DB to a SQL file.

A row is considered "manual" if its ID does NOT follow the doc_id-N pattern
used by ingest_parquet.py. This captures rows inserted via manual_inserts.sql,
ad-hoc session INSERTs, and rows from the old build_db.py with non-standard IDs.

Usage:
    python scripts/export_manual_rows.py                # Audit only (report drift)
    python scripts/export_manual_rows.py --export       # Export to manual_inserts_auto.sql
    python scripts/export_manual_rows.py --export --out scripts/manual_inserts.sql
"""

import argparse
import sqlite3
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PROD_DB = ROOT / "web" / "data" / "epstein_africa.db"
DEFAULT_OUT = ROOT / "scripts" / "manual_inserts_auto.sql"

COLUMNS = [
    "id", "doc_id", "sender", "subject", "to_recipients",
    "sent_at", "countries", "release_batch", "epstein_is_sender",
    "is_promotional", "all_participants", "body",
]


def escape_sql(val):
    """Escape a value for SQL INSERT."""
    if val is None:
        return "NULL"
    if isinstance(val, (int, float)):
        return str(int(val))
    s = str(val).replace("'", "''")
    return f"'{s}'"


def get_manual_rows(db_path):
    """Return all rows whose ID doesn't match the doc_id-N ingest pattern."""
    conn = sqlite3.connect(str(db_path))
    conn.row_factory = sqlite3.Row
    c = conn.cursor()
    c.execute("""
        SELECT * FROM emails
        WHERE id NOT LIKE doc_id || '-%'
        ORDER BY sent_at, id
    """)
    rows = [dict(r) for r in c.fetchall()]
    conn.close()
    return rows


def get_parquet_rows_count(db_path):
    """Return count of rows that match the ingest pattern."""
    conn = sqlite3.connect(str(db_path))
    c = conn.cursor()
    c.execute("SELECT COUNT(*) FROM emails WHERE id LIKE doc_id || '-%'")
    count = c.fetchone()[0]
    c.execute("SELECT COUNT(*) FROM emails")
    total = c.fetchone()[0]
    conn.close()
    return count, total


def export_sql(rows, out_path):
    """Write rows as SQL INSERT statements."""
    with open(out_path, "w") as f:
        f.write("-- Auto-generated by export_manual_rows.py\n")
        f.write(f"-- {len(rows)} manual rows exported\n")
        f.write("-- Re-run: python scripts/export_manual_rows.py --export\n\n")
        f.write("BEGIN TRANSACTION;\n\n")

        for row in rows:
            vals = ", ".join(escape_sql(row.get(col)) for col in COLUMNS)
            cols = ", ".join(COLUMNS)
            f.write(f"INSERT OR IGNORE INTO emails ({cols})\n")
            f.write(f"  VALUES ({vals});\n\n")

        f.write("COMMIT;\n\n")
        f.write("-- Rebuild FTS after running this file:\n")
        f.write("-- INSERT INTO emails_fts(emails_fts) VALUES('rebuild');\n")


def main():
    parser = argparse.ArgumentParser(description="Export manual rows from production DB")
    parser.add_argument("--export", action="store_true", help="Export to SQL file")
    parser.add_argument("--out", type=str, default=None, help="Output path")
    args = parser.parse_args()

    if not PROD_DB.exists():
        print(f"ERROR: {PROD_DB} not found")
        sys.exit(1)

    parquet_count, total = get_parquet_rows_count(PROD_DB)
    manual_rows = get_manual_rows(PROD_DB)

    print(f"Production DB: {PROD_DB}")
    print(f"  Total rows:          {total}")
    print(f"  Parquet-derived:     {parquet_count} (id matches doc_id-N pattern)")
    print(f"  Manual/non-standard: {len(manual_rows)}")

    null_body = [r for r in manual_rows if not r.get("body")]
    null_countries = [r for r in manual_rows if not r.get("countries")]
    if null_body:
        print(f"  WARNING: {len(null_body)} manual rows have NULL/empty body")
    if null_countries:
        print(f"  WARNING: {len(null_countries)} manual rows have NULL/empty countries")

    if args.export:
        out_path = Path(args.out) if args.out else DEFAULT_OUT
        export_sql(manual_rows, out_path)
        size_kb = out_path.stat().st_size / 1024
        print(f"\n  Exported {len(manual_rows)} rows to {out_path} ({size_kb:.0f} KB)")
    else:
        print(f"\n  Run with --export to generate SQL file.")


if __name__ == "__main__":
    main()
