"""Export manually inserted DB rows that are not in africa.parquet.

These rows were added directly via SQL and would be lost if build_db.py
is re-run. This script exports them as INSERT statements so they can be
re-applied after a rebuild.

Usage:
    python3 scripts/export_manual_rows.py
    # writes scripts/manual_inserts.sql
"""

import sqlite3
import pandas as pd
from pathlib import Path

DB_PATH = Path("web/data/epstein_africa.db")
PARQUET_PATH = Path("data/jmail/africa.parquet")
OUTPUT_PATH = Path("scripts/manual_inserts.sql")

def main():
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row

    # Get all DB doc_ids
    db_rows = conn.execute("SELECT * FROM emails").fetchall()
    columns = db_rows[0].keys() if db_rows else []

    # Get parquet doc_ids
    if PARQUET_PATH.exists():
        pdf = pd.read_parquet(PARQUET_PATH, columns=["doc_id"])
        parquet_ids = set(pdf["doc_id"].tolist())
    else:
        print(f"Warning: {PARQUET_PATH} not found, exporting ALL rows")
        parquet_ids = set()

    # Find rows whose doc_id is NOT in parquet (= manually inserted)
    manual = [r for r in db_rows if r["doc_id"] not in parquet_ids]

    print(f"DB total: {len(db_rows)}")
    print(f"Parquet doc_ids: {len(parquet_ids)}")
    print(f"Manual rows: {len(manual)}")

    if not manual:
        print("No manual rows found.")
        return

    lines = [
        "-- Auto-generated by export_manual_rows.py",
        f"-- {len(manual)} rows not in africa.parquet",
        "",
    ]

    for row in manual:
        vals = []
        for col in columns:
            v = row[col]
            if v is None:
                vals.append("NULL")
            elif isinstance(v, (int, float)):
                vals.append(str(v))
            else:
                escaped = str(v).replace("'", "''")
                vals.append(f"'{escaped}'")
        cols_str = ", ".join(columns)
        vals_str = ", ".join(vals)
        lines.append(
            f"INSERT OR IGNORE INTO emails ({cols_str}) VALUES ({vals_str});"
        )

    lines.append("")
    lines.append("-- Rebuild FTS after re-inserting")
    lines.append("INSERT INTO emails_fts(emails_fts) VALUES('rebuild');")
    lines.append("")

    OUTPUT_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {len(manual)} INSERT statements to {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
